=head1 Procedure for Building Coupling Data

Create the CoreSEED GTOs

    genome.download core --clear /vol/core-seed/FIGdisk/FIG/Data/Organisms GTOtemp

Add the subsystems

    genome.download subsystems GTOtemp /vol/core-seed/FIGdisk/FIG/Data/Subsystems

Insure the RepGen.200 GTOs have the latest points of interest.

    genome.blast poi --reset --clear poi_seeds.fa Kmers/GTO200 GTOtemp

Generate the coupling table.

    kmers.reps coupling -n CLOSE --names poi_seeds.fa GTOtemp >Global/couples.tbl

Add the points of interest to the Core GTOs

    genome.blast poi --clear poi_seeds.fa GTOtemp GTOcouple

Prepare the GTO directory for use in the website.

    kmers.reps prepare -n CLOSE Global/couples.tbl GTOcouple

Erase the temp directory.

    rm GTOtemp/*

